### ISSUE TITLE
HTML Tables

### ISSUE THREAD

**Issue by Karna98** [cdli-gh/blog#5]
@sagar-sehgal  HTML Tables are breaking down. 
https://cdli-gh.github.io/blog/gsoc20/search/index 

PS  : 
Dashed table doesn't support rows within row (as I have to use \<br>).

**Comment by thesagarsehgal** [comment]
@Karna98 Thanks for bringing this to notice. I will look into this by tomorrow and get a solution for you.

Thanks.

**Comment by thesagarsehgal** [comment]
@Karna98 I have tried on one of the possible solutions. The issue was with the Markdown parser which was `kramdown`. `kramdown` does not support some of the new features. So I have updated it to `CommonMarkGhPages`.

Please have a look now, that you can create tables with rowspan and colspan easily without any issues.

**Comment by Karna98** [comment]
Thanks @sagar-sehgal .
 
Note : `:technologist:` Emoji is not supported, replaced with `:man_technologist:`

**Comment by thesagarsehgal** [comment]
So, I am closing the issue.
